### ISSUE TITLE
Jeżeli to widzisz to dobrze :)

### ISSUE THREAD

**Issue by IgorKowalczyk** [Arbuzio12312/arbuzio12312.github.io#1]
Za to że to jedyna forma teraz komunikacji z tobą to jest ten Github, bo Discord zablokował mi konto i muszę przeprowadzić weryfikacje telefonem, jak mi się uda przywrócić konto to się odezwę :)

PS. Nie używaj Jquery

**Comment by Arbuzio12312** [comment]
aha XD blokneli ci? jak coś to masz 🍉Wredny ruchacz Arbuz🍉#1844    
            
          
     
      
       
        Dnia 23 stycznia 2020 21:25 Igor Kowalczyk &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Za to że to jedyna forma teraz komunikacji z tobą to jest ten Github, bo Discord zablokował mi konto i muszę przeprowadzić weryfikacje telefonem, jak mi się uda przywrócić konto to się odezwę :) 
 PS. Nie używaj Jquery

**Comment by IgorKowalczyk** [comment]
Jeszcze, zmień nick na bez arbuzów bo nie jestem wstanie dodać cię z tymi arbuzami...
